mv: 'ExplaGraphs/data/dev.tsv' and 'ExplaGraphs/data/dev.tsv' are the same file
09/20/2022 18:51:59 - WARNING - __main__ -   Process rank: -1, device: cuda, n_gpu: 1, distributed training: False, 16-bits training: False
09/20/2022 18:51:59 - INFO - pytorch_transformers.modeling_utils -   loading configuration file ExplaGraphs/models/sp_model/config.json
09/20/2022 18:51:59 - INFO - pytorch_transformers.modeling_utils -   Model config {
  "architectures": [
    "RobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "eos_token_id": 2,
  "finetuning_task": "eg",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "num_labels": 2,
  "output_attentions": false,
  "output_hidden_states": false,
  "pad_token_id": 1,
  "torchscript": false,
  "type_vocab_size": 1,
  "vocab_size": 50265
}

09/20/2022 18:51:59 - INFO - pytorch_transformers.tokenization_utils -   Model name 'ExplaGraphs/models/sp_model' not found in model shortcut name list (roberta-base, roberta-large, roberta-large-mnli). Assuming 'ExplaGraphs/models/sp_model' is a path or url to a directory containing tokenizer files.
09/20/2022 18:51:59 - INFO - pytorch_transformers.tokenization_utils -   loading file ExplaGraphs/models/sp_model/vocab.json
09/20/2022 18:51:59 - INFO - pytorch_transformers.tokenization_utils -   loading file ExplaGraphs/models/sp_model/merges.txt
09/20/2022 18:51:59 - INFO - pytorch_transformers.tokenization_utils -   loading file ExplaGraphs/models/sp_model/added_tokens.json
09/20/2022 18:51:59 - INFO - pytorch_transformers.tokenization_utils -   loading file ExplaGraphs/models/sp_model/special_tokens_map.json
09/20/2022 18:51:59 - INFO - pytorch_transformers.modeling_utils -   loading weights file ExplaGraphs/models/sp_model/pytorch_model.bin
Traceback (most recent call last):
  File "ExplaGraphs/structured_model/run_joint_model.py", line 672, in <module>
    main()
  File "ExplaGraphs/structured_model/run_joint_model.py", line 592, in main
    model = model_class.from_pretrained(args.model_name_or_path, from_tf=bool('.ckpt' in args.model_name_or_path),
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/explagraph/lib/python3.8/site-packages/pytorch_transformers/modeling_utils.py", line 474, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/cluster/raid/home/zhivar.sourati/logical-fallacy-identification/AMR_parsers_and_graphs/ExplaGraphs/structured_model/joint_model.py", line 59, in __init__
    self.relation_embeddings = torch.load("./data/relations.pt").to(device)
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/explagraph/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/explagraph/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/explagraph/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './data/relations.pt'
mv: cannot stat 'ExplaGraphs/models/sp_model/prediction_nodes_dev.lst': No such file or directory
09/20/2022 18:52:08 - WARNING - __main__ -   Process rank: -1, device: cuda, n_gpu: 1, distributed training: False, 16-bits training: False
09/20/2022 18:52:08 - INFO - pytorch_transformers.modeling_utils -   loading configuration file ExplaGraphs/models/sp_model/config.json
09/20/2022 18:52:08 - INFO - pytorch_transformers.modeling_utils -   Model config {
  "architectures": [
    "RobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "eos_token_id": 2,
  "finetuning_task": "eg",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "num_labels": 2,
  "output_attentions": false,
  "output_hidden_states": false,
  "pad_token_id": 1,
  "torchscript": false,
  "type_vocab_size": 1,
  "vocab_size": 50265
}

09/20/2022 18:52:08 - INFO - pytorch_transformers.tokenization_utils -   Model name 'ExplaGraphs/models/sp_model' not found in model shortcut name list (roberta-base, roberta-large, roberta-large-mnli). Assuming 'ExplaGraphs/models/sp_model' is a path or url to a directory containing tokenizer files.
09/20/2022 18:52:08 - INFO - pytorch_transformers.tokenization_utils -   loading file ExplaGraphs/models/sp_model/vocab.json
09/20/2022 18:52:08 - INFO - pytorch_transformers.tokenization_utils -   loading file ExplaGraphs/models/sp_model/merges.txt
09/20/2022 18:52:08 - INFO - pytorch_transformers.tokenization_utils -   loading file ExplaGraphs/models/sp_model/added_tokens.json
09/20/2022 18:52:08 - INFO - pytorch_transformers.tokenization_utils -   loading file ExplaGraphs/models/sp_model/special_tokens_map.json
09/20/2022 18:52:08 - INFO - pytorch_transformers.modeling_utils -   loading weights file ExplaGraphs/models/sp_model/pytorch_model.bin
Traceback (most recent call last):
  File "ExplaGraphs/structured_model/run_joint_model.py", line 672, in <module>
    main()
  File "ExplaGraphs/structured_model/run_joint_model.py", line 592, in main
    model = model_class.from_pretrained(args.model_name_or_path, from_tf=bool('.ckpt' in args.model_name_or_path),
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/explagraph/lib/python3.8/site-packages/pytorch_transformers/modeling_utils.py", line 474, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/cluster/raid/home/zhivar.sourati/logical-fallacy-identification/AMR_parsers_and_graphs/ExplaGraphs/structured_model/joint_model.py", line 59, in __init__
    self.relation_embeddings = torch.load("./data/relations.pt").to(device)
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/explagraph/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/explagraph/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/explagraph/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './data/relations.pt'
mv: cannot stat 'ExplaGraphs/models/sp_model/prediction_edges_dev.lst': No such file or directory
