{
    "os": "Linux-5.4.0-121-generic-x86_64-with-glibc2.31",
    "python": "3.10.4",
    "heartbeatAt": "2022-09-19T16:10:55.619860",
    "startedAt": "2022-09-19T16:10:55.127900",
    "docker": null,
    "cpu_count": 8,
    "cuda": null,
    "args": [],
    "state": "running",
    "program": "/cluster/raid/home/zhivar.sourati/logical-fallacy-identification/AMR_parsers_and_graphs/train.py",
    "codePath": "AMR_parsers_and_graphs/train.py",
    "git": {
        "remote": "git@github.com:usc-isi-i2/logical-fallacy-identification.git",
        "commit": "fa9daa1b6dedeccf492306f9f17d83d469afb122"
    },
    "email": null,
    "root": "/cluster/raid/home/zhivar.sourati/logical-fallacy-identification",
    "host": "login",
    "username": "zhivar.sourati",
    "executable": "/cluster/raid/home/zhivar.sourati/anaconda3/envs/general/bin/python"
}
