{
    "os": "Linux-5.4.0-121-generic-x86_64-with-glibc2.31",
    "python": "3.10.4",
    "heartbeatAt": "2022-09-20T22:24:26.516019",
    "startedAt": "2022-09-20T22:24:26.062175",
    "docker": null,
    "gpu": "Tesla V100-PCIE-16GB",
    "gpu_count": 5,
    "cpu_count": 16,
    "cuda": null,
    "args": [],
    "state": "running",
    "program": "/cluster/raid/home/zhivar.sourati/logical-fallacy-identification/AMR_parsers_and_graphs/gcn.py",
    "codePath": "AMR_parsers_and_graphs/gcn.py",
    "git": {
        "remote": "git@github.com:usc-isi-i2/logical-fallacy-identification.git",
        "commit": "237b4d675230f4649ad7feefe7cdb914294775ca"
    },
    "email": "zhivarsourati@gmail.com",
    "root": "/cluster/raid/home/zhivar.sourati/logical-fallacy-identification",
    "host": "node03",
    "username": "zhivar.sourati",
    "executable": "/cluster/raid/home/zhivar.sourati/anaconda3/envs/general/bin/python"
}
